version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    # Look for `build.gradle` and `gradle.properties` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"

  # Enable version updates for Docker (if applicable)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
